spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/gmall?characterBncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://192.168.0.139:3306/gmall0722?characterBncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver